year = 2026
base_url = "https://juny8916.github.io/Dent_QR_Gen_Sejong_CJ/"

name_column = "치과명"
sheet_index = 0
input_excel_path = "data/clinics.xlsx"

generate_qr_named = true
caption_font_path = ""
caption_font_size = 28

generate_outbox = true
outbox_mode = "changed"
outbox_root = "output/outbox"
